using System.Text.Json;

namespace CodeMaster.McpServer.Tools;

/// <summary>
/// MCP tool that returns a CodeMaster-oriented analysis template for a natural language requirement.
/// </summary>
public class AnalyzeTool
{
    public static McpTool Definition => new()
    {
        Name = "analyze_requirements",
        Description = "Analyze a business requirement and return a CodeMaster-oriented schema design checklist and example payloads for create_or_update_entity. This tool does not create data by itself.",
        InputType = typeof(AnalyzeInput),
        InputSchema = JsonSerializer.SerializeToNode(new
        {
            type = "object",
            properties = new
            {
                description = new { type = "string", description = "Business requirement to analyze." },
                projectId = new { oneOf = new object[] { new { type = "integer" }, new { type = "string" } }, description = "Optional target project id." },
                databaseType = new { type = "string", description = "Optional target database type: SqlServer, MySQL, PostgreSQL, SQLite, or Oracle." }
            },
            required = new[] { "description" }
        })!
    };

    public Task<object?> HandleAsync(object? input)
    {
        var args = (AnalyzeInput?)input ?? throw new ArgumentException("Invalid input");
        return Task.FromResult<object?>(new
        {
            success = true,
            message = "Use this checklist to design entities, then call create_or_update_entity for each entity and generate_code for each generated entity.",
            projectId = args.ProjectId?.ToString(),
            databaseType = args.DatabaseType,
            description = args.Description,
            checklist = new[]
            {
                "Identify aggregate roots and child tables. Example: Order is the aggregate root and OrderItem is the child table.",
                "Define only business fields. Id, audit fields, soft-delete fields, and tenant fields are generated by CodeMaster metadata switches.",
                "Choose entity capabilities explicitly: writable/tree entities require hasPrimaryKey=true; keyed read-only keeps getById; keyless read-only is list/query/export only.",
                "Use PascalCase field names in metadata. Generated Vue code will use camelCase.",
                "Use long foreign keys named {EntityName}Id.",
                "For select-table fields, set formControlType=select-table, relatedEntityName, relatedEntityIdField=Id, and relatedDisplayFields.",
                "For dictionary fields, use formControlType=select and enumValues or a dictionary configuration.",
                "For computed fields, use fieldCategory=Computed with a numeric type and an arithmetic formula such as [Price]*[Quantity].",
                "For child statistics, create the child and one-to-many relation first, then use fieldCategory=Aggregate with Sum, Avg, or Concat and the child entity id/field.",
                "For one-to-many pages, create child entity first, then add relations on the parent entity.",
                "After metadata changes, call generate_code and inspect validation output."
            },
            example = new
            {
                projectId = args.ProjectId?.ToString() ?? "1",
                moduleName = "OrderManagement",
                moduleDescription = "Order management",
                entityName = "Order",
                description = "Order master table",
                hasPrimaryKey = true,
                isReadOnly = false,
                hasAudit = true,
                hasSoftDelete = true,
                fields = new object[]
                {
                    new { name = "OrderNo", dataType = "string", maxLength = 32, isRequired = true, showInList = true, showInSearch = true, orderNum = 1 },
                    new { name = "CustomerId", dataType = "long", formControlType = "select-table", relatedEntityName = "Customer", relatedEntityIdField = "Id", relatedDisplayFields = new[] { "Name", "Type" }, showInList = true, showInSearch = true, orderNum = 2 },
                    new { name = "TotalAmount", dataType = "decimal", precision = 18, scale = 2, formControlType = "number", showInList = true, orderNum = 3 },
                    new { name = "Status", dataType = "string", formControlType = "select", enumValues = "Pending,Paid,Shipped,Completed,Cancelled", isMultiple = false, showInList = true, showInSearch = true, orderNum = 4 },
                    new { name = "OrderTime", dataType = "DateTime", formControlType = "datetime", showInList = true, showInSearch = true, orderNum = 5 },
                    new { name = "TaxAmount", dataType = "decimal", precision = 18, scale = 2, formControlType = "number", fieldCategory = "Computed", formula = "[TotalAmount]*0.06", showInList = true, showInAddForm = true, showInEditForm = true, orderNum = 6 }
                },
                relations = new[]
                {
                    new { childEntityName = "OrderItem", foreignKey = "OrderId" }
                }
            }
        });
    }
}

public class AnalyzeInput
{
    public string Description { get; set; } = string.Empty;
    public long? ProjectId { get; set; }
    public string? DatabaseType { get; set; }
}
