using System.Text.Json;
using CodeMaster.McpServer.Services;

namespace CodeMaster.McpServer.Tools;

public class AuthTool
{
    private readonly McpAuthStore _authStore;
    private readonly ProjectContextResolver _contextResolver;

    public AuthTool(McpAuthStore authStore, ProjectContextResolver contextResolver)
    {
        _authStore = authStore;
        _contextResolver = contextResolver;
    }

    public static McpTool LoginDefinition => new()
    {
        Name = "codemaster_login",
        Description = "Save a CodeMaster MCP token for a server. Paste the token generated from CodeMaster personal center. The token is validated before saving.",
        InputType = typeof(McpLoginInput),
        InputSchema = JsonSerializer.SerializeToNode(new
        {
            type = "object",
            properties = new
            {
                serverBaseUrl = new { type = "string", description = "CodeMaster server base URL. If omitted, read from .codemaster/project-context.json." },
                token = new { type = "string", description = "MCP token generated by CodeMaster personal center." },
                workspacePath = new { type = "string", description = "Optional generated project directory used to resolve serverBaseUrl." }
            },
            required = new[] { "token" }
        })!
    };

    public static McpTool LogoutDefinition => new()
    {
        Name = "codemaster_logout",
        Description = "Remove saved CodeMaster MCP token for a server, or all saved tokens when serverBaseUrl is omitted.",
        InputType = typeof(McpLogoutInput),
        InputSchema = JsonSerializer.SerializeToNode(new
        {
            type = "object",
            properties = new
            {
                serverBaseUrl = new { type = "string", description = "CodeMaster server base URL. If omitted, all saved tokens are removed." }
            }
        })!
    };

    public static McpTool WhoAmIDefinition => new()
    {
        Name = "codemaster_whoami",
        Description = "Validate and show the currently saved CodeMaster MCP identity.",
        InputType = typeof(McpWhoAmIInput),
        InputSchema = JsonSerializer.SerializeToNode(new
        {
            type = "object",
            properties = new
            {
                serverBaseUrl = new { type = "string", description = "CodeMaster server base URL. If omitted, read from project context or latest saved token." },
                workspacePath = new { type = "string", description = "Optional generated project directory used to resolve serverBaseUrl." }
            }
        })!
    };

    public static McpTool ResolveContextDefinition => new()
    {
        Name = "resolve_project_context",
        Description = "Read .codemaster/project-context.json from the current or provided generated project directory.",
        InputType = typeof(ResolveProjectContextInput),
        InputSchema = JsonSerializer.SerializeToNode(new
        {
            type = "object",
            properties = new
            {
                workspacePath = new { type = "string", description = "Optional generated project directory. Defaults to MCP server current directory." }
            }
        })!
    };

    public async Task<object> LoginAsync(object? input)
    {
        var args = (McpLoginInput?)input ?? throw new ArgumentException("Invalid input");
        var serverBaseUrl = await ResolveServerBaseUrlAsync(args.ServerBaseUrl, args.WorkspacePath);
        var whoami = await _authStore.ValidateAsync(serverBaseUrl, args.Token);

        await _authStore.SaveAsync(new McpAuthEntry
        {
            ServerBaseUrl = serverBaseUrl,
            Token = args.Token.Trim(),
            UserId = whoami.UserId,
            UserName = whoami.UserName,
            NickName = whoami.NickName,
            SavedAt = DateTime.UtcNow
        });

        return new
        {
            success = true,
            authFile = _authStore.AuthFilePath,
            user = whoami
        };
    }

    public async Task<object> LogoutAsync(object? input)
    {
        var args = (McpLogoutInput?)input ?? new McpLogoutInput();
        var removed = await _authStore.RemoveAsync(args.ServerBaseUrl);
        return new { success = true, removed, authFile = _authStore.AuthFilePath };
    }

    public async Task<object> WhoAmIAsync(object? input)
    {
        var args = (McpWhoAmIInput?)input ?? new McpWhoAmIInput();
        var serverBaseUrl = await TryResolveServerBaseUrlAsync(args.ServerBaseUrl, args.WorkspacePath);
        var entry = await _authStore.GetAsync(serverBaseUrl);
        if (entry == null)
            return new { success = false, message = "No CodeMaster MCP token saved. Use codemaster_login first.", authFile = _authStore.AuthFilePath };

        var whoami = await _authStore.ValidateAsync(entry.ServerBaseUrl, entry.Token);
        return new { success = true, authFile = _authStore.AuthFilePath, user = whoami };
    }

    public async Task<object> ResolveProjectContextAsync(object? input)
    {
        var args = (ResolveProjectContextInput?)input ?? new ResolveProjectContextInput();
        var context = await _contextResolver.ResolveAsync(args.WorkspacePath);
        return context == null
            ? new { success = false, message = ".codemaster/project-context.json was not found." }
            : new { success = true, context };
    }

    private async Task<string> ResolveServerBaseUrlAsync(string? serverBaseUrl, string? workspacePath)
    {
        var resolved = await TryResolveServerBaseUrlAsync(serverBaseUrl, workspacePath);
        if (string.IsNullOrWhiteSpace(resolved))
            throw new ArgumentException("serverBaseUrl is required when project context does not provide one.");

        return resolved;
    }

    private async Task<string?> TryResolveServerBaseUrlAsync(string? serverBaseUrl, string? workspacePath)
    {
        if (!string.IsNullOrWhiteSpace(serverBaseUrl))
            return McpAuthStore.NormalizeBaseUrl(serverBaseUrl);

        var context = await _contextResolver.ResolveAsync(workspacePath);
        return string.IsNullOrWhiteSpace(context?.ServerBaseUrl)
            ? null
            : McpAuthStore.NormalizeBaseUrl(context.ServerBaseUrl);
    }
}

public class McpLoginInput
{
    public string? ServerBaseUrl { get; set; }

    public string Token { get; set; } = string.Empty;

    public string? WorkspacePath { get; set; }
}

public class McpLogoutInput
{
    public string? ServerBaseUrl { get; set; }
}

public class McpWhoAmIInput
{
    public string? ServerBaseUrl { get; set; }

    public string? WorkspacePath { get; set; }
}

public class ResolveProjectContextInput
{
    public string? WorkspacePath { get; set; }
}
