using System.ComponentModel;
using ModelContextProtocol.Server;

namespace CodeMaster.McpServer.Tools;

[McpServerToolType]
public sealed class CodeMasterMcpTools
{
    [McpServerTool(Name = "codemaster_login")]
    [Description("Validate and save a CodeMaster MCP token generated in the CodeMaster personal center.")]
    public static Task<object?> LoginAsync(
        AuthTool tool,
        [Description("MCP token generated by CodeMaster.")] string token,
        [Description("Optional CodeMaster server URL. Defaults to the current project context.")] string? serverBaseUrl = null,
        [Description("Optional generated project directory.")] string? workspacePath = null)
    {
        return SafeInvokeAsync(() => tool.LoginAsync(new McpLoginInput
        {
            Token = token,
            ServerBaseUrl = serverBaseUrl,
            WorkspacePath = workspacePath
        }));
    }

    [McpServerTool(Name = "codemaster_logout")]
    [Description("Remove a saved CodeMaster MCP token.")]
    public static Task<object?> LogoutAsync(AuthTool tool, string? serverBaseUrl = null)
    {
        return SafeInvokeAsync(() => tool.LogoutAsync(new McpLogoutInput { ServerBaseUrl = serverBaseUrl }));
    }

    [McpServerTool(Name = "codemaster_whoami")]
    [Description("Validate and show the current CodeMaster MCP identity, tenant, roles, and permissions.")]
    public static Task<object?> WhoAmIAsync(
        AuthTool tool,
        string? serverBaseUrl = null,
        string? workspacePath = null)
    {
        return SafeInvokeAsync(() => tool.WhoAmIAsync(new McpWhoAmIInput
        {
            ServerBaseUrl = serverBaseUrl,
            WorkspacePath = workspacePath
        }));
    }

    [McpServerTool(Name = "resolve_project_context")]
    [Description("Read .codemaster/project-context.json from the current or provided generated project directory.")]
    public static Task<object?> ResolveProjectContextAsync(AuthTool tool, string? workspacePath = null)
    {
        return SafeInvokeAsync(() => tool.ResolveProjectContextAsync(new ResolveProjectContextInput { WorkspacePath = workspacePath }));
    }

    [McpServerTool(Name = "query_project")]
    [Description("Read CodeMaster projects, modules, entities, or fields through the authenticated WebApi.")]
    public static Task<object?> QueryProjectAsync(
        QueryTool tool,
        [Description("projects, modules, entities, or fields")] string level,
        string? projectId = null,
        string? moduleId = null,
        string? entityId = null,
        string? workspacePath = null)
    {
        return SafeInvokeAsync(() => tool.HandleAsync(new QueryInput
        {
            Level = level,
            ProjectId = ParseNullableId(projectId),
            ModuleId = ParseNullableId(moduleId),
            EntityId = ParseNullableId(entityId),
            WorkspacePath = workspacePath
        }));
    }

    [McpServerTool(Name = "analyze_requirements")]
    [Description("Analyze a requirement and return a CodeMaster entity-design checklist without changing data.")]
    public static Task<object?> AnalyzeRequirementsAsync(
        AnalyzeTool tool,
        string description,
        string? projectId = null,
        string? databaseType = null)
    {
        return SafeInvokeAsync(() => tool.HandleAsync(new AnalyzeInput
        {
            Description = description,
            ProjectId = ParseNullableId(projectId),
            DatabaseType = databaseType
        }));
    }

    [McpServerTool(Name = "save_project")]
    [Description("Create or update a CodeMaster project through the authenticated WebApi.")]
    public static Task<object?> SaveProjectAsync(
        ProjectTool tool,
        string? projectId = null,
        string? projectName = null,
        string? displayName = null,
        string? displayNameEn = null,
        string? description = null,
        string? descriptionEn = null,
        string? databaseType = null,
        string? connectionString = null,
        string? projectPath = null,
        string? logoPath = null,
        string? projectType = null,
        int? frontendPort = null,
        int? backendPort = null,
        string? workspacePath = null)
    {
        return SafeInvokeAsync(() => tool.HandleAsync(new ProjectToolInput
        {
            ProjectId = ParseId(projectId),
            ProjectName = projectName,
            DisplayName = displayName,
            DisplayNameEn = displayNameEn,
            Description = description,
            DescriptionEn = descriptionEn,
            DatabaseType = databaseType,
            ConnectionString = connectionString,
            ProjectPath = projectPath,
            LogoPath = logoPath,
            ProjectType = projectType,
            FrontendPort = frontendPort,
            BackendPort = backendPort,
            WorkspacePath = workspacePath
        }));
    }

    [McpServerTool(Name = "save_module")]
    [Description("Create or update a CodeMaster project module through the authenticated WebApi.")]
    public static Task<object?> SaveModuleAsync(
        ModuleTool tool,
        string moduleName,
        string? projectId = null,
        string? moduleId = null,
        string? moduleDescription = null,
        string? icon = null,
        int? orderNum = null,
        string? routePath = null,
        string? remark = null,
        string? workspacePath = null)
    {
        return SafeInvokeAsync(() => tool.HandleAsync(new ModuleToolInput
        {
            ProjectId = ParseId(projectId),
            ModuleId = ParseId(moduleId),
            ModuleName = moduleName,
            ModuleDescription = moduleDescription,
            Icon = icon,
            OrderNum = orderNum,
            RoutePath = routePath,
            Remark = remark,
            WorkspacePath = workspacePath
        }));
    }

    [McpServerTool(Name = "create_or_update_entity")]
    [Description("Create or update CodeMaster entity metadata, fields, controls, select-table result mappings, legacy one-to-many relations, and owned one-to-one relations through the authenticated WebApi.")]
    public static Task<object?> CreateOrUpdateEntityAsync(
        EntityTool tool,
        string? projectId = null,
        string? moduleId = null,
        string? moduleName = null,
        string? moduleDescription = null,
        string? moduleIcon = null,
        int? moduleOrderNum = null,
        string? entityId = null,
        string? entityName = null,
        string? description = null,
        string? tableName = null,
        bool? hasPrimaryKey = null,
        bool? isTree = null,
        bool? isReadOnly = null,
        bool? isMultiTenant = null,
        bool? hasDataPermission = null,
        bool? hasAudit = null,
        bool? hasSoftDelete = null,
        bool? generateFrontend = null,
        bool? isChildTable = null,
        string? frontendRoute = null,
        string? menuIcon = null,
        int? orderNum = null,
        string? remark = null,
        List<FieldInput>? fields = null,
        List<RelationInput>? relations = null,
        List<OwnedOneRelationInput>? ownedOneRelations = null,
        string? workspacePath = null)
    {
        return SafeInvokeAsync(() => tool.HandleAsync(new EntityToolInput
        {
            ProjectId = ParseId(projectId),
            ModuleId = ParseId(moduleId),
            ModuleName = moduleName,
            ModuleDescription = moduleDescription,
            ModuleIcon = moduleIcon,
            ModuleOrderNum = moduleOrderNum,
            EntityId = ParseId(entityId),
            EntityName = entityName,
            Description = description,
            TableName = tableName,
            HasPrimaryKey = hasPrimaryKey,
            IsTree = isTree,
            IsReadOnly = isReadOnly,
            IsMultiTenant = isMultiTenant,
            HasDataPermission = hasDataPermission,
            HasAudit = hasAudit,
            HasSoftDelete = hasSoftDelete,
            GenerateFrontend = generateFrontend,
            IsChildTable = isChildTable,
            FrontendRoute = frontendRoute,
            MenuIcon = menuIcon,
            OrderNum = orderNum,
            Remark = remark,
            Fields = fields,
            Relations = relations,
            OwnedOneRelations = ownedOneRelations,
            WorkspacePath = workspacePath
        }));
    }

    [McpServerTool(Name = "run_project_operation")]
    [Description("Run initialization, migration, build, start, stop, status, project menu sync, or project language sync on the local generated project.")]
    public static Task<object?> RunProjectOperationAsync(
        ProjectOperationTool tool,
        string operation,
        string? projectId = null,
        string? targetPath = null,
        int step = 0,
        string? workspacePath = null)
    {
        return SafeInvokeAsync(() => tool.HandleAsync(new ProjectOperationInput
        {
            Operation = operation,
            ProjectId = ParseId(projectId),
            TargetPath = targetPath,
            Step = step,
            WorkspacePath = workspacePath
        }));
    }

    [McpServerTool(Name = "generate_code")]
    [Description("Generate code locally from metadata and templates downloaded through the authenticated CodeMaster WebApi.")]
    public static Task<object?> GenerateCodeAsync(
        CodeGenTool tool,
        string? entityId = null,
        string? entityName = null,
        string? projectId = null,
        string? moduleId = null,
        string? mode = null,
        bool validateBuild = true,
        bool validateFrontendBuild = false,
        int buildTimeoutSeconds = 300,
        string? workspacePath = null)
    {
        return SafeInvokeAsync(() => tool.HandleAsync(new CodeGenInput
        {
            EntityId = ParseId(entityId),
            EntityName = entityName,
            ProjectId = ParseId(projectId),
            ModuleId = ParseId(moduleId),
            Mode = mode,
            ValidateBuild = validateBuild,
            ValidateFrontendBuild = validateFrontendBuild,
            BuildTimeoutSeconds = buildTimeoutSeconds,
            WorkspacePath = workspacePath
        }));
    }

    [McpServerTool(Name = "get_project_structure")]
    [Description("Read the complete authenticated project structure and inspect generated files in the local workspace.")]
    public static Task<object?> GetProjectStructureAsync(
        ProjectStructureTool tool,
        string? projectId = null,
        bool includeGeneratedFiles = true,
        string? workspacePath = null)
    {
        return SafeInvokeAsync(() => tool.HandleAsync(new ProjectStructureInput
        {
            ProjectId = ParseId(projectId),
            IncludeGeneratedFiles = includeGeneratedFiles,
            WorkspacePath = workspacePath
        }));
    }

    private static long ParseId(string? value)
    {
        return long.TryParse(value, out var parsed) ? parsed : 0;
    }

    private static long? ParseNullableId(string? value)
    {
        return long.TryParse(value, out var parsed) ? parsed : null;
    }

    private static async Task<object?> SafeInvokeAsync<T>(Func<Task<T>> action)
    {
        try
        {
            return await action();
        }
        catch (Exception ex)
        {
            return new { success = false, message = ex.Message };
        }
    }
}
