// <auto-generated />
using System;
using CodeMaster.Migrator.Persistence.EfCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CodeMaster.Migrator.Migrations
{
    [DbContext(typeof(CodeMasterDbContext))]
    [Migration("20260223052431_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("CodeMaster.Domain.Entities.CodeGen.GenTable", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("CreateBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("create_by");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("create_time");

                    b.Property<long?>("CreateUserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("create_user_id");

                    b.Property<string>("DeleteBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("delete_by");

                    b.Property<DateTime?>("DeleteTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("delete_time");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("entity_name");

                    b.Property<string>("FunctionAuthor")
                        .HasColumnType("TEXT")
                        .HasColumnName("function_author");

                    b.Property<string>("FunctionName")
                        .HasColumnType("TEXT")
                        .HasColumnName("function_name");

                    b.Property<string>("GenPath")
                        .HasColumnType("TEXT")
                        .HasColumnName("gen_path");

                    b.Property<int>("IsChild")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_child");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_deleted");

                    b.Property<int>("IsReadOnly")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_read_only");

                    b.Property<int>("IsTree")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_tree");

                    b.Property<long>("ModuleId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("module_id");

                    b.Property<int>("OnlyDto")
                        .HasColumnType("INTEGER")
                        .HasColumnName("only_dto");

                    b.Property<string>("Remark")
                        .HasColumnType("TEXT")
                        .HasColumnName("remark");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER")
                        .HasColumnName("status");

                    b.Property<string>("TableComment")
                        .HasColumnType("TEXT")
                        .HasColumnName("table_comment");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("table_name");

                    b.Property<long>("TenantId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TreeNameField")
                        .HasColumnType("TEXT")
                        .HasColumnName("tree_name_field");

                    b.Property<string>("TreeParentField")
                        .HasColumnType("TEXT")
                        .HasColumnName("tree_parent_field");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("update_by");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("update_time");

                    b.HasKey("Id");

                    b.ToTable("gen_tables", (string)null);
                });

            modelBuilder.Entity("CodeMaster.Domain.Entities.CodeGen.GenTableColumn", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("ColumnComment")
                        .HasColumnType("TEXT")
                        .HasColumnName("column_comment");

                    b.Property<string>("ColumnName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("column_name");

                    b.Property<string>("ColumnType")
                        .HasColumnType("TEXT")
                        .HasColumnName("column_type");

                    b.Property<string>("CreateBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("create_by");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("create_time");

                    b.Property<long?>("CreateUserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("create_user_id");

                    b.Property<string>("CsharpType")
                        .HasColumnType("TEXT")
                        .HasColumnName("csharp_type");

                    b.Property<string>("DeleteBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("delete_by");

                    b.Property<DateTime?>("DeleteTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("delete_time");

                    b.Property<string>("DictType")
                        .HasColumnType("TEXT")
                        .HasColumnName("dict_type");

                    b.Property<string>("HtmlType")
                        .HasColumnType("TEXT")
                        .HasColumnName("html_type");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_deleted");

                    b.Property<int>("IsIncrement")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_increment");

                    b.Property<int>("IsPk")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_pk");

                    b.Property<int>("IsQuery")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_query");

                    b.Property<int>("IsRequired")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_required");

                    b.Property<string>("PropertyName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("property_name");

                    b.Property<string>("QueryType")
                        .HasColumnType("TEXT")
                        .HasColumnName("query_type");

                    b.Property<string>("Remark")
                        .HasColumnType("TEXT")
                        .HasColumnName("remark");

                    b.Property<int>("ShowInAdd")
                        .HasColumnType("INTEGER")
                        .HasColumnName("show_in_add");

                    b.Property<int>("ShowInDetail")
                        .HasColumnType("INTEGER")
                        .HasColumnName("show_in_detail");

                    b.Property<int>("ShowInEdit")
                        .HasColumnType("INTEGER")
                        .HasColumnName("show_in_edit");

                    b.Property<int>("ShowInList")
                        .HasColumnType("INTEGER")
                        .HasColumnName("show_in_list");

                    b.Property<int>("Sort")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sort");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER")
                        .HasColumnName("status");

                    b.Property<long>("TableId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("table_id");

                    b.Property<long>("TenantId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("tenant_id");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("update_by");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("update_time");

                    b.HasKey("Id");

                    b.ToTable("gen_table_columns", (string)null);
                });

            modelBuilder.Entity("CodeMaster.Domain.Entities.Monitor.SysLoginLog", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Browser")
                        .HasColumnType("TEXT")
                        .HasColumnName("browser");

                    b.Property<string>("CreateBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("create_by");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("create_time");

                    b.Property<long?>("CreateUserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("create_user_id");

                    b.Property<string>("DeleteBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("delete_by");

                    b.Property<DateTime?>("DeleteTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("delete_time");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_deleted");

                    b.Property<string>("LoginIp")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("login_ip");

                    b.Property<string>("LoginLocation")
                        .HasColumnType("TEXT")
                        .HasColumnName("login_location");

                    b.Property<DateTime>("LoginTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("login_time");

                    b.Property<string>("Msg")
                        .HasColumnType("TEXT")
                        .HasColumnName("msg");

                    b.Property<string>("Os")
                        .HasColumnType("TEXT")
                        .HasColumnName("os");

                    b.Property<string>("Remark")
                        .HasColumnType("TEXT")
                        .HasColumnName("remark");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER")
                        .HasColumnName("status");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("update_by");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("update_time");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("user_name");

                    b.HasKey("Id");

                    b.ToTable("sys_login_log", (string)null);
                });

            modelBuilder.Entity("CodeMaster.Domain.Entities.Monitor.SysOperLog", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("BusinessType")
                        .HasColumnType("INTEGER")
                        .HasColumnName("business_type");

                    b.Property<string>("CreateBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("create_by");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("create_time");

                    b.Property<long?>("CreateUserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("create_user_id");

                    b.Property<string>("DeleteBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("delete_by");

                    b.Property<DateTime?>("DeleteTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("delete_time");

                    b.Property<long>("Elapsed")
                        .HasColumnType("INTEGER")
                        .HasColumnName("elapsed");

                    b.Property<string>("ErrorMsg")
                        .HasColumnType("TEXT")
                        .HasColumnName("error_msg");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_deleted");

                    b.Property<string>("JsonResult")
                        .HasColumnType("TEXT")
                        .HasColumnName("json_result");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("method");

                    b.Property<string>("OperIp")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("oper_ip");

                    b.Property<string>("OperLocation")
                        .HasColumnType("TEXT")
                        .HasColumnName("oper_location");

                    b.Property<string>("OperName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("oper_name");

                    b.Property<string>("OperParam")
                        .HasColumnType("TEXT")
                        .HasColumnName("oper_param");

                    b.Property<DateTime>("OperTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("oper_time");

                    b.Property<string>("OperUrl")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("oper_url");

                    b.Property<int>("OperatorType")
                        .HasColumnType("INTEGER")
                        .HasColumnName("operator_type");

                    b.Property<string>("Remark")
                        .HasColumnType("TEXT")
                        .HasColumnName("remark");

                    b.Property<string>("RequestMethod")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("request_method");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("update_by");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("update_time");

                    b.HasKey("Id");

                    b.ToTable("sys_oper_log", (string)null);
                });

            modelBuilder.Entity("CodeMaster.Domain.Entities.Monitor.SysTask", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime?>("BeginTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("begin_time");

                    b.Property<string>("CreateBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("create_by");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("create_time");

                    b.Property<long?>("CreateUserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("create_user_id");

                    b.Property<string>("CronExpression")
                        .HasColumnType("TEXT")
                        .HasColumnName("cron_expression");

                    b.Property<string>("DeleteBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("delete_by");

                    b.Property<DateTime?>("DeleteTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("delete_time");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("end_time");

                    b.Property<int>("IntervalSecond")
                        .HasColumnType("INTEGER")
                        .HasColumnName("interval_second");

                    b.Property<string>("InvokeTarget")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("invoke_target");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_deleted");

                    b.Property<string>("JobGroup")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("job_group");

                    b.Property<DateTime?>("LastRunTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_run_time");

                    b.Property<string>("Remark")
                        .HasColumnType("TEXT")
                        .HasColumnName("remark");

                    b.Property<int>("RunTimes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("run_times");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER")
                        .HasColumnName("status");

                    b.Property<string>("TaskName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("task_name");

                    b.Property<int>("TaskType")
                        .HasColumnType("INTEGER")
                        .HasColumnName("task_type");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("update_by");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("update_time");

                    b.HasKey("Id");

                    b.ToTable("sys_tasks", (string)null);
                });

            modelBuilder.Entity("CodeMaster.Domain.Entities.Monitor.SysTaskLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("create_time");

                    b.Property<double>("Elapsed")
                        .HasColumnType("REAL")
                        .HasColumnName("elapsed");

                    b.Property<string>("InvokeTarget")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("invoke_target");

                    b.Property<string>("JobMessage")
                        .HasColumnType("TEXT")
                        .HasColumnName("job_message");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER")
                        .HasColumnName("status");

                    b.Property<long>("TaskId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("task_id");

                    b.Property<string>("TaskName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("task_name");

                    b.HasKey("Id");

                    b.ToTable("sys_task_logs", (string)null);
                });

            modelBuilder.Entity("CodeMaster.Domain.Entities.CodeGen.EntityField", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("CreateBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("create_by");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("create_time");

                    b.Property<long?>("CreateUserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("create_user_id");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("data_type");

                    b.Property<string>("DefaultValue")
                        .HasColumnType("TEXT")
                        .HasColumnName("default_value");

                    b.Property<string>("DeleteBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("delete_by");

                    b.Property<DateTime?>("DeleteTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("delete_time");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("FormControlType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("form_control_type");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsEmail")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_email");

                    b.Property<bool>("IsIgnore")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_ignore");

                    b.Property<bool>("IsNullable")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_nullable");

                    b.Property<bool>("IsPhone")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_phone");

                    b.Property<bool>("IsPrimaryKey")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_primary_key");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_required");

                    b.Property<bool>("IsSystemField")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_system_field");

                    b.Property<int?>("ListWidth")
                        .HasColumnType("INTEGER")
                        .HasColumnName("list_width");

                    b.Property<int?>("MaxLength")
                        .HasColumnType("INTEGER")
                        .HasColumnName("max_length");

                    b.Property<string>("MaxValue")
                        .HasColumnType("TEXT")
                        .HasColumnName("max_value");

                    b.Property<string>("MinValue")
                        .HasColumnType("TEXT")
                        .HasColumnName("min_value");

                    b.Property<long>("ModuleEntityId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("module_entity_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<int>("OrderNum")
                        .HasColumnType("INTEGER")
                        .HasColumnName("order_num");

                    b.Property<int?>("Precision")
                        .HasColumnType("INTEGER")
                        .HasColumnName("precision");

                    b.Property<string>("RegexPattern")
                        .HasColumnType("TEXT")
                        .HasColumnName("regex_pattern");

                    b.Property<string>("Remark")
                        .HasColumnType("TEXT")
                        .HasColumnName("remark");

                    b.Property<int?>("Scale")
                        .HasColumnType("INTEGER")
                        .HasColumnName("scale");

                    b.Property<string>("SelectDataSource")
                        .HasColumnType("TEXT")
                        .HasColumnName("select_data_source");

                    b.Property<string>("SelectOptions")
                        .HasColumnType("TEXT")
                        .HasColumnName("select_options");

                    b.Property<bool>("ShowInAddForm")
                        .HasColumnType("INTEGER")
                        .HasColumnName("show_in_add_form");

                    b.Property<bool>("ShowInDetail")
                        .HasColumnType("INTEGER")
                        .HasColumnName("show_in_detail");

                    b.Property<bool>("ShowInEditForm")
                        .HasColumnType("INTEGER")
                        .HasColumnName("show_in_edit_form");

                    b.Property<bool>("ShowInList")
                        .HasColumnType("INTEGER")
                        .HasColumnName("show_in_list");

                    b.Property<bool>("ShowInSearch")
                        .HasColumnType("INTEGER")
                        .HasColumnName("show_in_search");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("update_by");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("update_time");

                    b.HasKey("Id");

                    b.ToTable("sys_entity_field", (string)null);
                });

            modelBuilder.Entity("CodeMaster.Domain.Entities.CodeGen.ModuleEntity", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("CreateBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("create_by");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("create_time");

                    b.Property<long?>("CreateUserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("create_user_id");

                    b.Property<string>("DeleteBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("delete_by");

                    b.Property<DateTime?>("DeleteTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("delete_time");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("FrontendRoute")
                        .HasColumnType("TEXT")
                        .HasColumnName("frontend_route");

                    b.Property<bool>("GenerateFrontend")
                        .HasColumnType("INTEGER")
                        .HasColumnName("generate_frontend");

                    b.Property<bool>("HasDataPermission")
                        .HasColumnType("INTEGER")
                        .HasColumnName("has_data_permission");

                    b.Property<bool>("HasTenant")
                        .HasColumnType("INTEGER")
                        .HasColumnName("has_tenant");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsGenerated")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_generated");

                    b.Property<bool>("IsReadOnly")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_read_only");

                    b.Property<bool>("IsTree")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_tree");

                    b.Property<DateTime?>("LastGeneratedTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_generated_time");

                    b.Property<string>("MenuIcon")
                        .HasColumnType("TEXT")
                        .HasColumnName("menu_icon");

                    b.Property<long>("ModuleId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("module_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<int>("OrderNum")
                        .HasColumnType("INTEGER")
                        .HasColumnName("order_num");

                    b.Property<long>("ProjectId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("project_id");

                    b.Property<string>("Remark")
                        .HasColumnType("TEXT")
                        .HasColumnName("remark");

                    b.Property<string>("TableName")
                        .HasColumnType("TEXT")
                        .HasColumnName("table_name");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("update_by");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("update_time");

                    b.HasKey("Id");

                    b.ToTable("sys_module_entity", (string)null);
                });

            modelBuilder.Entity("CodeMaster.Domain.Entities.CodeGen.Project", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int?>("BackendPort")
                        .HasColumnType("INTEGER")
                        .HasColumnName("backend_port");

                    b.Property<string>("ConnectionString")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("connection_string");

                    b.Property<string>("CreateBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("create_by");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("create_time");

                    b.Property<long?>("CreateUserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("create_user_id");

                    b.Property<int>("DatabaseType")
                        .HasColumnType("INTEGER")
                        .HasColumnName("database_type");

                    b.Property<string>("DeleteBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("delete_by");

                    b.Property<DateTime?>("DeleteTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("delete_time");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("DescriptionEn")
                        .HasColumnType("TEXT")
                        .HasColumnName("description_en");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("display_name");

                    b.Property<string>("DisplayNameEn")
                        .HasColumnType("TEXT")
                        .HasColumnName("display_name_en");

                    b.Property<int?>("FrontendPort")
                        .HasColumnType("INTEGER")
                        .HasColumnName("frontend_port");

                    b.Property<string>("InitError")
                        .HasColumnType("TEXT")
                        .HasColumnName("init_error");

                    b.Property<DateTime?>("InitializedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("initialized_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_deleted");

                    b.Property<string>("LogoPath")
                        .HasColumnType("TEXT")
                        .HasColumnName("logo_path");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("project_name");

                    b.Property<string>("ProjectPath")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("project_path");

                    b.Property<int>("ProjectType")
                        .HasColumnType("INTEGER")
                        .HasColumnName("project_type");

                    b.Property<string>("Remark")
                        .HasColumnType("TEXT")
                        .HasColumnName("remark");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER")
                        .HasColumnName("status");

                    b.Property<long>("TenantId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("tenant_id");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("update_by");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("update_time");

                    b.HasKey("Id");

                    b.ToTable("sys_project", (string)null);
                });

            modelBuilder.Entity("CodeMaster.Domain.Entities.CodeGen.ProjectModule", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("CreateBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("create_by");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("create_time");

                    b.Property<long?>("CreateUserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("create_user_id");

                    b.Property<string>("DeleteBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("delete_by");

                    b.Property<DateTime?>("DeleteTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("delete_time");

                    b.Property<string>("Icon")
                        .HasColumnType("TEXT")
                        .HasColumnName("icon");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsSynced")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_synced");

                    b.Property<DateTime?>("LastSyncTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_sync_time");

                    b.Property<string>("ModuleDescription")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("module_description");

                    b.Property<string>("ModuleName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("module_name");

                    b.Property<int>("OrderNum")
                        .HasColumnType("INTEGER")
                        .HasColumnName("order_num");

                    b.Property<long>("ProjectId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("project_id");

                    b.Property<string>("Remark")
                        .HasColumnType("TEXT")
                        .HasColumnName("remark");

                    b.Property<string>("RoutePath")
                        .HasColumnType("TEXT")
                        .HasColumnName("route_path");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("update_by");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("update_time");

                    b.HasKey("Id");

                    b.ToTable("project_modules", (string)null);
                });

            modelBuilder.Entity("CodeMaster.Domain.Entities.System.SysDept", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Ancestors")
                        .HasColumnType("TEXT")
                        .HasColumnName("ancestors");

                    b.Property<string>("CreateBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("create_by");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("create_time");

                    b.Property<long?>("CreateUserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("create_user_id");

                    b.Property<string>("DeleteBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("delete_by");

                    b.Property<DateTime?>("DeleteTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("delete_time");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<long?>("ParentId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("parent_id");

                    b.Property<string>("Remark")
                        .HasColumnType("TEXT")
                        .HasColumnName("remark");

                    b.Property<long>("TenantId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("tenant_id");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("update_by");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("update_time");

                    b.HasKey("Id");

                    b.ToTable("sys_depts", (string)null);
                });

            modelBuilder.Entity("CodeMaster.Domain.Entities.System.SysDictData", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("CreateBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("create_by");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("create_time");

                    b.Property<long?>("CreateUserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("create_user_id");

                    b.Property<string>("DeleteBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("delete_by");

                    b.Property<DateTime?>("DeleteTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("delete_time");

                    b.Property<string>("DictType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("dict_type");

                    b.Property<int>("IsDefault")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_default");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("label");

                    b.Property<string>("LangKey")
                        .HasColumnType("TEXT")
                        .HasColumnName("lang_key");

                    b.Property<string>("Remark")
                        .HasColumnType("TEXT")
                        .HasColumnName("remark");

                    b.Property<int>("Sort")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sort");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER")
                        .HasColumnName("status");

                    b.Property<long>("TenantId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("tenant_id");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("update_by");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("update_time");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.ToTable("sys_dict_datas", (string)null);
                });

            modelBuilder.Entity("CodeMaster.Domain.Entities.System.SysDictType", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("CreateBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("create_by");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("create_time");

                    b.Property<long?>("CreateUserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("create_user_id");

                    b.Property<string>("DeleteBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("delete_by");

                    b.Property<DateTime?>("DeleteTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("delete_time");

                    b.Property<string>("DictName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("dict_name");

                    b.Property<string>("DictType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("dict_type");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_deleted");

                    b.Property<string>("LangKey")
                        .HasColumnType("TEXT")
                        .HasColumnName("lang_key");

                    b.Property<string>("Remark")
                        .HasColumnType("TEXT")
                        .HasColumnName("remark");

                    b.Property<int>("Sort")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sort");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER")
                        .HasColumnName("status");

                    b.Property<long>("TenantId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("tenant_id");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("update_by");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("update_time");

                    b.HasKey("Id");

                    b.ToTable("sys_dict_types", (string)null);
                });

            modelBuilder.Entity("CodeMaster.Domain.Entities.System.SysFile", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("AccessUrl")
                        .HasColumnType("TEXT")
                        .HasColumnName("access_url");

                    b.Property<string>("CreateBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("create_by");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("create_time");

                    b.Property<long?>("CreateUserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("create_user_id");

                    b.Property<string>("DeleteBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("delete_by");

                    b.Property<DateTime?>("DeleteTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("delete_time");

                    b.Property<string>("FileCategory")
                        .HasColumnType("TEXT")
                        .HasColumnName("file_category");

                    b.Property<string>("FileExt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("file_ext");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("file_name");

                    b.Property<long>("FileSize")
                        .HasColumnType("INTEGER")
                        .HasColumnName("file_size");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("file_type");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("file_url");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_deleted");

                    b.Property<string>("RealName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("real_name");

                    b.Property<string>("Remark")
                        .HasColumnType("TEXT")
                        .HasColumnName("remark");

                    b.Property<string>("StorePath")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("store_path");

                    b.Property<int>("StoreType")
                        .HasColumnType("INTEGER")
                        .HasColumnName("store_type");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("update_by");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("update_time");

                    b.HasKey("Id");

                    b.ToTable("sys_file", (string)null);
                });

            modelBuilder.Entity("CodeMaster.Domain.Entities.System.SysLang", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("CreateBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("create_by");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("create_time");

                    b.Property<long?>("CreateUserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("create_user_id");

                    b.Property<string>("DeleteBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("delete_by");

                    b.Property<DateTime?>("DeleteTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("delete_time");

                    b.Property<int>("IsDefault")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_default");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_deleted");

                    b.Property<int>("IsEnabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_enabled");

                    b.Property<string>("LangCode")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("lang_code");

                    b.Property<string>("LangName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("lang_name");

                    b.Property<string>("Remark")
                        .HasColumnType("TEXT")
                        .HasColumnName("remark");

                    b.Property<int>("Sort")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sort");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("update_by");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("update_time");

                    b.HasKey("Id");

                    b.ToTable("sys_langs", (string)null);
                });

            modelBuilder.Entity("CodeMaster.Domain.Entities.System.SysLangText", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT")
                        .HasColumnName("category");

                    b.Property<string>("CreateBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("create_by");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("create_time");

                    b.Property<long?>("CreateUserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("create_user_id");

                    b.Property<string>("DeleteBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("delete_by");

                    b.Property<DateTime?>("DeleteTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("delete_time");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_deleted");

                    b.Property<string>("LangCode")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("lang_code");

                    b.Property<string>("LangKey")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("lang_key");

                    b.Property<string>("LangValue")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("lang_value");

                    b.Property<string>("Remark")
                        .HasColumnType("TEXT")
                        .HasColumnName("remark");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("update_by");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("update_time");

                    b.HasKey("Id");

                    b.ToTable("sys_lang_texts", (string)null);
                });

            modelBuilder.Entity("CodeMaster.Domain.Entities.System.SysMenu", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Ancestors")
                        .HasColumnType("TEXT")
                        .HasColumnName("ancestors");

                    b.Property<string>("Component")
                        .HasColumnType("TEXT")
                        .HasColumnName("component");

                    b.Property<string>("CreateBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("create_by");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("create_time");

                    b.Property<long?>("CreateUserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("create_user_id");

                    b.Property<string>("DeleteBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("delete_by");

                    b.Property<DateTime?>("DeleteTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("delete_time");

                    b.Property<string>("Icon")
                        .HasColumnType("TEXT")
                        .HasColumnName("icon");

                    b.Property<int>("IsCache")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_cache");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_deleted");

                    b.Property<int>("IsFrame")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_frame");

                    b.Property<string>("MenuName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("menu_name");

                    b.Property<int>("MenuScope")
                        .HasColumnType("INTEGER")
                        .HasColumnName("menu_scope");

                    b.Property<string>("MenuType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("menu_type");

                    b.Property<int>("OrderNum")
                        .HasColumnType("INTEGER")
                        .HasColumnName("order_num");

                    b.Property<long?>("ParentId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("parent_id");

                    b.Property<string>("Path")
                        .HasColumnType("TEXT")
                        .HasColumnName("path");

                    b.Property<string>("Perms")
                        .HasColumnType("TEXT")
                        .HasColumnName("perms");

                    b.Property<string>("Query")
                        .HasColumnType("TEXT")
                        .HasColumnName("query");

                    b.Property<string>("Remark")
                        .HasColumnType("TEXT")
                        .HasColumnName("remark");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER")
                        .HasColumnName("status");

                    b.Property<string>("TitleKey")
                        .HasColumnType("TEXT")
                        .HasColumnName("title_key");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("update_by");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("update_time");

                    b.Property<int>("Visible")
                        .HasColumnType("INTEGER")
                        .HasColumnName("visible");

                    b.HasKey("Id");

                    b.ToTable("sys_menus", (string)null);
                });

            modelBuilder.Entity("CodeMaster.Domain.Entities.System.SysPost", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("CreateBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("create_by");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("create_time");

                    b.Property<long?>("CreateUserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("create_user_id");

                    b.Property<int>("DataScope")
                        .HasColumnType("INTEGER")
                        .HasColumnName("data_scope");

                    b.Property<string>("DeleteBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("delete_by");

                    b.Property<DateTime?>("DeleteTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("delete_time");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_deleted");

                    b.Property<string>("PostName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("post_name");

                    b.Property<string>("Remark")
                        .HasColumnType("TEXT")
                        .HasColumnName("remark");

                    b.Property<long>("TenantId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("tenant_id");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("update_by");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("update_time");

                    b.HasKey("Id");

                    b.ToTable("sys_posts", (string)null);
                });

            modelBuilder.Entity("CodeMaster.Domain.Entities.System.SysRole", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("CreateBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("create_by");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("create_time");

                    b.Property<long?>("CreateUserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("create_user_id");

                    b.Property<int>("DataScope")
                        .HasColumnType("INTEGER")
                        .HasColumnName("data_scope");

                    b.Property<int>("DelFlag")
                        .HasColumnType("INTEGER")
                        .HasColumnName("del_flag");

                    b.Property<string>("DeleteBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("delete_by");

                    b.Property<DateTime?>("DeleteTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("delete_time");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Remark")
                        .HasColumnType("TEXT")
                        .HasColumnName("remark");

                    b.Property<string>("RoleKey")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("role_key");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("role_name");

                    b.Property<int>("RoleSort")
                        .HasColumnType("INTEGER")
                        .HasColumnName("role_sort");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER")
                        .HasColumnName("status");

                    b.Property<long>("TenantId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("tenant_id");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("update_by");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("update_time");

                    b.HasKey("Id");

                    b.ToTable("sys_roles", (string)null);
                });

            modelBuilder.Entity("CodeMaster.Domain.Entities.System.SysRoleMenu", b =>
                {
                    b.Property<long>("RoleId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("role_id");

                    b.Property<long>("MenuId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("menu_id");

                    b.HasKey("RoleId", "MenuId");

                    b.ToTable("sys_role_menus", (string)null);
                });

            modelBuilder.Entity("CodeMaster.Domain.Entities.System.SysTenant", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("ConfigId")
                        .HasColumnType("TEXT")
                        .HasColumnName("config_id");

                    b.Property<string>("ConnectionString")
                        .HasColumnType("TEXT")
                        .HasColumnName("connection_string");

                    b.Property<string>("CreateBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("create_by");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("create_time");

                    b.Property<long?>("CreateUserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("create_user_id");

                    b.Property<int?>("DbType")
                        .HasColumnType("INTEGER")
                        .HasColumnName("db_type");

                    b.Property<string>("DeleteBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("delete_by");

                    b.Property<DateTime?>("DeleteTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("delete_time");

                    b.Property<DateTime?>("ExpireTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("expire_time");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_deleted");

                    b.Property<int>("IsolationType")
                        .HasColumnType("INTEGER")
                        .HasColumnName("isolation_type");

                    b.Property<string>("Remark")
                        .HasColumnType("TEXT")
                        .HasColumnName("remark");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER")
                        .HasColumnName("status");

                    b.Property<string>("TenantCode")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("tenant_code");

                    b.Property<long>("TenantId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TenantName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("tenant_name");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("update_by");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("update_time");

                    b.HasKey("Id");

                    b.ToTable("sys_tenants", (string)null);
                });

            modelBuilder.Entity("CodeMaster.Domain.Entities.System.SysUser", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Avatar")
                        .HasColumnType("TEXT")
                        .HasColumnName("avatar");

                    b.Property<string>("CreateBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("create_by");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("create_time");

                    b.Property<long?>("CreateUserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("create_user_id");

                    b.Property<int>("DelFlag")
                        .HasColumnType("INTEGER")
                        .HasColumnName("del_flag");

                    b.Property<string>("DeleteBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("delete_by");

                    b.Property<DateTime?>("DeleteTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("delete_time");

                    b.Property<string>("DeptAncestors")
                        .HasColumnType("TEXT")
                        .HasColumnName("dept_ancestors");

                    b.Property<long?>("DeptId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("dept_id");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("LoginDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("login_date");

                    b.Property<string>("LoginIp")
                        .HasColumnType("TEXT")
                        .HasColumnName("login_ip");

                    b.Property<string>("NickName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("nick_name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("password");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT")
                        .HasColumnName("phone_number");

                    b.Property<long?>("PostId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("post_id");

                    b.Property<string>("Remark")
                        .HasColumnType("TEXT")
                        .HasColumnName("remark");

                    b.Property<int?>("Sex")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sex");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER")
                        .HasColumnName("status");

                    b.Property<long>("TenantId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("tenant_id");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("update_by");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("update_time");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("user_name");

                    b.Property<string>("UserType")
                        .HasColumnType("TEXT")
                        .HasColumnName("user_type");

                    b.HasKey("Id");

                    b.ToTable("sys_users", (string)null);
                });

            modelBuilder.Entity("CodeMaster.Domain.Entities.System.SysUserRole", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_id");

                    b.Property<long>("RoleId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId");

                    b.ToTable("sys_user_roles", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
